
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEAR BINOP CHARACTER COMMA CREATE DISPLAY DOT ELSE FOR FROM ID IF IN LDELIMITER LSLASHES MINUS NODE PLUS RDELIMITER RSLASHES SEPARATOR WHILEtest : BEAR functionfunction : term\n               | IF function COMMA function SEPARATOR ELSE function\n               | FOR LSLASHES term IN function RSLASHES term\n               | WHILE LSLASHES term BINOP term RSLASHES termadd : graph PLUS LDELIMITER file RDELIMITER\n            | graph PLUS IDcreate : CREATE LSLASHES ID RSLASHES\n                | CREATE LSLASHES ID FROM file RSLASHES\n                | CREATEremove : graph MINUS nodedisplay : DISPLAY graphgraph : IDfile : ID DOT IDnode : NODE IDterm : add\n            | remove\n            | display\n            | file\n            | graph\n            | node\n            | create'
    
_lr_action_items = {'BEAR':([0,],[2,]),'$end':([1,3,4,8,9,10,11,12,13,14,15,18,25,26,27,33,34,35,42,47,52,53,54,55,],[0,-1,-2,-16,-17,-18,-19,-20,-21,-22,-13,-10,-12,-13,-15,-7,-11,-14,-8,-6,-9,-3,-4,-5,]),'IF':([2,5,29,38,49,],[5,5,5,5,5,]),'FOR':([2,5,29,38,49,],[6,6,6,6,6,]),'WHILE':([2,5,29,38,49,],[7,7,7,7,7,]),'DISPLAY':([2,5,20,21,29,38,39,49,50,51,],[16,16,16,16,16,16,16,16,16,16,]),'ID':([2,5,16,17,20,21,22,24,28,29,32,38,39,43,49,50,51,],[15,15,26,27,15,15,33,35,36,15,41,15,15,41,15,15,15,]),'NODE':([2,5,20,21,23,29,38,39,49,50,51,],[17,17,17,17,17,17,17,17,17,17,17,]),'CREATE':([2,5,20,21,29,38,39,49,50,51,],[18,18,18,18,18,18,18,18,18,18,]),'COMMA':([4,8,9,10,11,12,13,14,15,18,19,25,26,27,33,34,35,42,47,52,53,54,55,],[-2,-16,-17,-18,-19,-20,-21,-22,-13,-10,29,-12,-13,-15,-7,-11,-14,-8,-6,-9,-3,-4,-5,]),'SEPARATOR':([4,8,9,10,11,12,13,14,15,18,25,26,27,33,34,35,37,42,47,52,53,54,55,],[-2,-16,-17,-18,-19,-20,-21,-22,-13,-10,-12,-13,-15,-7,-11,-14,44,-8,-6,-9,-3,-4,-5,]),'RSLASHES':([4,8,9,10,11,12,13,14,15,18,25,26,27,33,34,35,36,42,45,46,47,48,52,53,54,55,],[-2,-16,-17,-18,-19,-20,-21,-22,-13,-10,-12,-13,-15,-7,-11,-14,42,-8,50,51,-6,52,-9,-3,-4,-5,]),'LSLASHES':([6,7,18,],[20,21,28,]),'IN':([8,9,10,11,12,13,14,15,18,25,26,27,30,33,34,35,42,47,52,],[-16,-17,-18,-19,-20,-21,-22,-13,-10,-12,-13,-15,38,-7,-11,-14,-8,-6,-9,]),'BINOP':([8,9,10,11,12,13,14,15,18,25,26,27,31,33,34,35,42,47,52,],[-16,-17,-18,-19,-20,-21,-22,-13,-10,-12,-13,-15,39,-7,-11,-14,-8,-6,-9,]),'PLUS':([12,15,],[22,-13,]),'MINUS':([12,15,],[23,-13,]),'DOT':([15,41,],[24,24,]),'LDELIMITER':([22,],[32,]),'RDELIMITER':([35,40,],[-14,47,]),'FROM':([36,],[43,]),'ELSE':([44,],[49,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'test':([0,],[1,]),'function':([2,5,29,38,49,],[3,19,37,45,53,]),'term':([2,5,20,21,29,38,39,49,50,51,],[4,4,30,31,4,4,46,4,54,55,]),'add':([2,5,20,21,29,38,39,49,50,51,],[8,8,8,8,8,8,8,8,8,8,]),'remove':([2,5,20,21,29,38,39,49,50,51,],[9,9,9,9,9,9,9,9,9,9,]),'display':([2,5,20,21,29,38,39,49,50,51,],[10,10,10,10,10,10,10,10,10,10,]),'file':([2,5,20,21,29,32,38,39,43,49,50,51,],[11,11,11,11,11,40,11,11,48,11,11,11,]),'graph':([2,5,16,20,21,29,38,39,49,50,51,],[12,12,25,12,12,12,12,12,12,12,12,]),'node':([2,5,20,21,23,29,38,39,49,50,51,],[13,13,13,13,34,13,13,13,13,13,13,]),'create':([2,5,20,21,29,38,39,49,50,51,],[14,14,14,14,14,14,14,14,14,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> test","S'",1,None,None,None),
  ('test -> BEAR function','test',2,'p_define','BEAR.py',80),
  ('function -> term','function',1,'p_function','BEAR.py',86),
  ('function -> IF function COMMA function SEPARATOR ELSE function','function',7,'p_function','BEAR.py',87),
  ('function -> FOR LSLASHES term IN function RSLASHES term','function',7,'p_function','BEAR.py',88),
  ('function -> WHILE LSLASHES term BINOP term RSLASHES term','function',7,'p_function','BEAR.py',89),
  ('add -> graph PLUS LDELIMITER file RDELIMITER','add',5,'p_add','BEAR.py',95),
  ('add -> graph PLUS ID','add',3,'p_add','BEAR.py',96),
  ('create -> CREATE LSLASHES ID RSLASHES','create',4,'p_create','BEAR.py',101),
  ('create -> CREATE LSLASHES ID FROM file RSLASHES','create',6,'p_create','BEAR.py',102),
  ('create -> CREATE','create',1,'p_create','BEAR.py',103),
  ('remove -> graph MINUS node','remove',3,'p_remove','BEAR.py',111),
  ('display -> DISPLAY graph','display',2,'p_display','BEAR.py',115),
  ('graph -> ID','graph',1,'p_graph','BEAR.py',119),
  ('file -> ID DOT ID','file',3,'p_file','BEAR.py',123),
  ('node -> NODE ID','node',2,'p_node','BEAR.py',126),
  ('term -> add','term',1,'p_term','BEAR.py',130),
  ('term -> remove','term',1,'p_term','BEAR.py',131),
  ('term -> display','term',1,'p_term','BEAR.py',132),
  ('term -> file','term',1,'p_term','BEAR.py',133),
  ('term -> graph','term',1,'p_term','BEAR.py',134),
  ('term -> node','term',1,'p_term','BEAR.py',135),
  ('term -> create','term',1,'p_term','BEAR.py',136),
]
